# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27207486eb3cffa2488c7ab2bf2fa80db10ae1c27b25d0610e82d7643d4d68bce678c5e6c02faa3a674a9d646e641bd051d835f2c75ea1db497b3afdadb0b74c

test:
  secret_key_base: 630710e9a411fd63bb1dc3af7a65b997d491714d7a1174fcfbe25d69d9749dac048b5a260eb7ec824b0bd00a05d18213d1a5234e4aec803563706c3800034322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
